## simple mnist handwritten viz
https://tensorspace.org/html/playground/trainingLeNet.html

In [3]:
import torch

In [4]:
torch.__version__

'2.0.0+cu117'

In [5]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [6]:
# gives me the dimensions of the tensor
scalar.ndim

0

In [7]:
# gives me the tensor number  
scalar.item()

7

In [8]:
# vectors
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[5,8],[7,1]])
matrix

tensor([[5, 8],
        [7, 1]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
threed_tensor = torch.tensor([[[4,5,5],[9,7,4],[1,6,0]]])
threed_tensor

tensor([[[4, 5, 5],
         [9, 7, 4],
         [1, 6, 0]]])

In [15]:
threed_tensor.ndim

3

In [16]:
threed_tensor.shape

torch.Size([1, 3, 3])

In [17]:
random_tensors = torch.rand(size=(4,3))
random_tensors

tensor([[0.2670, 0.5454, 0.5399],
        [0.7176, 0.0354, 0.0419],
        [0.8753, 0.0070, 0.9808],
        [0.0012, 0.8730, 0.9759]])

In [18]:
random_tensors.shape

torch.Size([4, 3])

In [19]:
type(random_tensors.shape)

torch.Size

In [20]:
random_tensors.dtype

torch.float32

In [21]:
random_tensors.ndim

2

In [22]:
d3_rand_tensor = torch.rand(size=(4,3,5,1))
d3_rand_tensor

tensor([[[[0.9887],
          [0.6984],
          [0.0371],
          [0.4375],
          [0.1190]],

         [[0.8731],
          [0.4513],
          [0.3749],
          [0.3249],
          [0.9370]],

         [[0.8581],
          [0.3291],
          [0.3408],
          [0.2253],
          [0.6568]]],


        [[[0.3054],
          [0.6441],
          [0.7703],
          [0.5348],
          [0.8499]],

         [[0.9046],
          [0.2395],
          [0.3549],
          [0.2015],
          [0.8025]],

         [[0.4064],
          [0.6268],
          [0.0532],
          [0.7144],
          [0.1765]]],


        [[[0.3681],
          [0.0730],
          [0.9662],
          [0.6938],
          [0.3050]],

         [[0.8613],
          [0.0359],
          [0.0725],
          [0.3773],
          [0.4595]],

         [[0.8107],
          [0.0299],
          [0.1437],
          [0.2966],
          [0.7585]]],


        [[[0.3410],
          [0.4859],
          [0.5725],
          [0.799

In [23]:
d3_rand_tensor.ndim

4

In [24]:
zeros = torch.zeros(size=(5,7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zeros.shape

torch.Size([5, 7])

In [26]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.shape

torch.Size([3, 3])

In [28]:
ranging = torch.arange(0,1,0.2)
ranging

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])