## simple mnist handwritten viz
https://tensorspace.org/html/playground/trainingLeNet.html

In [3]:
import torch

In [4]:
torch.__version__

'2.0.0+cu117'

In [5]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [6]:
# gives me the dimensions of the tensor
scalar.ndim

0

In [7]:
# gives me the tensor number  
scalar.item()

7

In [8]:
# vectors
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[5,8],[7,1]])
matrix

tensor([[5, 8],
        [7, 1]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
threed_tensor = torch.tensor([[[4,5,5],[9,7,4],[1,6,0]]])
threed_tensor

tensor([[[4, 5, 5],
         [9, 7, 4],
         [1, 6, 0]]])

In [15]:
threed_tensor.ndim

3

In [16]:
threed_tensor.shape

torch.Size([1, 3, 3])

In [17]:
random_tensors = torch.rand(size=(4,3))
random_tensors

tensor([[0.7339, 0.7714, 0.3559],
        [0.9158, 0.7074, 0.6932],
        [0.3809, 0.8034, 0.3433],
        [0.8506, 0.5122, 0.2355]])

In [18]:
random_tensors.shape

torch.Size([4, 3])

In [19]:
type(random_tensors.shape)

torch.Size

In [20]:
random_tensors.dtype

torch.float32

In [21]:
random_tensors.ndim

2

In [22]:
d3_rand_tensor = torch.rand(size=(4,3,5,1))
d3_rand_tensor

tensor([[[[0.9668],
          [0.2017],
          [0.0683],
          [0.5490],
          [0.3981]],

         [[0.8656],
          [0.2708],
          [0.1627],
          [0.0657],
          [0.0172]],

         [[0.1191],
          [0.6005],
          [0.4204],
          [0.2412],
          [0.4924]]],


        [[[0.9131],
          [0.6922],
          [0.9998],
          [0.4006],
          [0.1007]],

         [[0.8500],
          [0.3884],
          [0.9096],
          [0.4557],
          [0.6202]],

         [[0.9859],
          [0.2179],
          [0.6301],
          [0.3615],
          [0.8195]]],


        [[[0.7845],
          [0.1214],
          [0.4216],
          [0.4499],
          [0.2113]],

         [[0.3108],
          [0.5413],
          [0.2220],
          [0.9238],
          [0.6502]],

         [[0.1861],
          [0.1603],
          [0.9291],
          [0.6119],
          [0.6389]]],


        [[[0.6069],
          [0.6587],
          [0.7139],
          [0.284

In [23]:
d3_rand_tensor.ndim

4

In [24]:
zeros = torch.zeros(size=(5,7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zeros.shape

torch.Size([5, 7])

In [26]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.shape

torch.Size([3, 3])

In [28]:
ranging = torch.arange(0,1,0.2)
ranging , ranging.shape

(tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000]), torch.Size([5]))

In [29]:
like_zeros = torch.zeros_like(input=ranging)
like_zeros , like_zeros.shape

(tensor([0., 0., 0., 0., 0.]), torch.Size([5]))

In [30]:
torch.zeros(size=ranging.shape)

tensor([0., 0., 0., 0., 0.])

In [31]:
tensor_x = torch.tensor([1, 2, 3],
                        dtype=None,
                        device='cpu',
                        requires_grad=False)
tensor_x.shape , tensor_x.dtype , tensor_x.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [32]:
# mathematical operations on Tensors
tensor_x + 10 , tensor_x * 10 , tensor_x - 10 

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [33]:
torch.multiply(tensor_x,2)

tensor([2, 4, 6])

In [34]:
tensor_y = tensor_x * tensor_x
tensor_y

tensor([1, 4, 9])

In [35]:
torch.matmul(tensor_x,tensor_y)

tensor(36)

In [36]:
# it's not recommended to do that
tensor_x @ tensor_y

tensor(36)

In [37]:
tensor_a = torch.tensor(([1, 2, 3],[4, 5, 6]))
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
tensor_d = torch.tensor(([7, 4, 3],[5, 5, 3]))
tensor_d

tensor([[7, 4, 3],
        [5, 5, 3]])

In [39]:
torch.matmul(tensor_a,tensor_d)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tensor_b = torch.transpose(tensor_d,0,1)
tensor_b

tensor([[7, 5],
        [4, 5],
        [3, 3]])

In [ ]:
torch.matmul(tensor_a,tensor_b)

tensor([[24, 24],
        [66, 63]])

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x2 = torch.t(x)
x2

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
torch.mm(x,x2)

tensor([[14, 32],
        [32, 77]])

In [ ]:
torch.manual_seed(42)

In [ ]:
from torch import nn 
tensor_a.shape

torch.Size([2, 3])

In [ ]:
tensor_A = torch.rand(size =(3,2)) # 3 m , 2 n  (2,6)
linear = nn.Linear(in_features=2,
                   out_features=6)
x = tensor_A
output = linear(x)
output

tensor([[-0.7547, -0.0861, -0.3664,  0.1088,  0.2499, -0.4849],
        [-0.4863, -0.0699, -0.6034,  0.2668,  0.3025, -0.4456],
        [-0.6967, -0.0235, -0.4670,  0.1641,  0.1851, -0.3990]],
       grad_fn=<AddmmBackward0>)

In [ ]:
c = torch.arange(0,100,10)
print(c)
c =c.max()
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor(90)

In [ ]:
c.type(torch.float64).mean()

tensor(90., dtype=torch.float64)

In [ ]:
c = c.type(torch.float32)
c.dtype

torch.float32

In [40]:
# argmax
c = torch.arange(0,100,10)
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
print(f'the maximum index in the tensor is {c.argmax()}')

the maximum index in the tensor is 9


In [42]:
print(f'the minimum index in the tensor is {c.argmin()}')

the minimum index in the tensor is 0
