In [1]:
import torch

In [2]:
torch.__version__

'2.0.0+cu117'

In [3]:
# scalar 
scalar = torch.tensor(6)
scalar.item() 

6

In [4]:
# how to create a vector of tensors ?
vector = torch.tensor([7,7])
vector , vector.ndim 

(tensor([7, 7]), 1)

In [5]:
# how to identify the shape of the tensor ?
vector.shape , scalar.shape

(torch.Size([2]), torch.Size([]))

In [6]:
# matrix 
matrix = torch.tensor([[4,7],[5,6]])
matrix , matrix.ndim

(tensor([[4, 7],
         [5, 6]]),
 2)

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
d3_tensor = torch.tensor([[ [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [9]:
# creating a random tensor

random_tensor = torch.rand(size=(4,3))
random_tensor

tensor([[0.4787, 0.7051, 0.4018],
        [0.2715, 0.0968, 0.3920],
        [0.7136, 0.1191, 0.5082],
        [0.0028, 0.8883, 0.6538]])

In [10]:
# check the shape
random_tensor.shape , random_tensor.ndim

(torch.Size([4, 3]), 2)

5 min read : https://pytorch.org/docs/stable/tensors.html

In [11]:
random_tensor.dtype

torch.float32

RGB images = [red , green , blue]

In [12]:
x_tensor = torch.rand(size=(224,224,3))
x_tensor.ndim 

3

In [13]:
# zeros 
zero_tensor = torch.zeros(size=(2,2,8))
zero_tensor , zero_tensor.shape , zero_tensor.ndim , zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [14]:
# ones 
ones_tensor = torch.ones(size=(2,2,8))
ones_tensor , ones_tensor.shape , ones_tensor.ndim , ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [15]:
# arange
t_tensor = torch.arange(0,10,1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
r_tensor = torch.tensor(data=[4,5,7],
                        dtype=torch.float64,
                        device='cpu',
                        requires_grad=False
                        )
r_tensor , r_tensor.dtype , r_tensor.device

(tensor([4., 5., 7.], dtype=torch.float64), torch.float64, device(type='cpu'))

# tensor operations
1. multiply
2. addition
3. subtraction
4. division

In [17]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [18]:
x = x + 10
x

tensor([11, 12, 13])

In [19]:
x = x - 2
x 

tensor([ 9, 10, 11])

In [20]:
x = x * 2
x

tensor([18, 20, 22])

In [21]:
x = x / 2
x

tensor([ 9., 10., 11.])

In [22]:
y = x * x
y

tensor([ 81., 100., 121.])

In [23]:
x = torch.multiply(x, 10)
x

tensor([ 90., 100., 110.])

In [24]:
x = torch.matmul(x ,x)
x

tensor(30200.)

In [25]:
x.shape , x.ndim

(torch.Size([]), 0)

In [26]:
tensor_a = torch.rand(size=(2,3))
tensor_a , tensor_a.shape

(tensor([[0.7803, 0.8704, 0.3096],
         [0.6074, 0.4854, 0.4840]]),
 torch.Size([2, 3]))

In [27]:
tensor_b = torch.rand(size=(3,8))
tensor_b , tensor_b.shape

(tensor([[0.0510, 0.0410, 0.7496, 0.0462, 0.8712, 0.8344, 0.7209, 0.2828],
         [0.6697, 0.9886, 0.2701, 0.4583, 0.4285, 0.4218, 0.9019, 0.4748],
         [0.2983, 0.1353, 0.5481, 0.4691, 0.2245, 0.1248, 0.3822, 0.6167]]),
 torch.Size([3, 8]))

In [28]:
tensor_f = torch.matmul(tensor_a,tensor_b)
tensor_f

tensor([[0.7150, 0.9343, 0.9897, 0.5802, 1.1223, 1.0568, 1.4658, 0.8249],
        [0.5004, 0.5702, 0.8517, 0.4776, 0.8459, 0.7719, 1.0606, 0.7007]])

In [29]:
# manual seed generation
torch.manual_seed(42)

random_tensor = torch.rand((2,3))
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [30]:
from torch import nn

In [31]:
linear_layer = nn.Linear(in_features=6,out_features=4)

tensor_L = torch.rand(size=(4,6))

x = linear_layer(tensor_L)
x

tensor([[ 0.6558,  0.0566,  0.1838, -0.5983],
        [ 0.6037,  0.2153, -0.0014, -0.6023],
        [ 0.5914,  0.0809,  0.1573, -0.5555],
        [ 0.8549,  0.0615,  0.2566, -0.5615]], grad_fn=<AddmmBackward0>)

In [32]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [33]:
v.min()

tensor(0)

In [34]:
v.max()

tensor(14)

In [35]:
max_index = v.argmax()
max_index

tensor(7)

In [36]:
min_index = v.argmin()
min_index

tensor(0)

In [37]:
float_tensor = torch.arange(0.,10,1.)
float_tensor , float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [38]:
float_tensor = torch.arange(0,10,1)
float_tensor , float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [57]:
# transpose
random_tensor , random_tensor.shape

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 torch.Size([2, 3]))

In [59]:
random_tensor_transpose = torch.transpose(random_tensor,dim0=0,dim1=1)
random_tensor_transpose , random_tensor_transpose.shape 

(tensor([[0.8823, 0.9593],
         [0.9150, 0.3904],
         [0.3829, 0.6009]]),
 torch.Size([3, 2]))

In [61]:
random_tensor_transpose_v2 = random_tensor.t()
random_tensor_transpose_v2 , random_tensor_transpose_v2.shape 

(tensor([[0.8823, 0.9593],
         [0.9150, 0.3904],
         [0.3829, 0.6009]]),
 torch.Size([3, 2]))

In [66]:
# mean of some tensor
mean_tensor = torch.arange(0,10,1)
mean_tensor , mean_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [67]:
mean_tensor_f32 = mean_tensor.type(torch.float32)
mean_tensor_f32 , mean_tensor_f32.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [68]:
mean_tensor_r = mean_tensor_f32.mean()
mean_tensor_r

tensor(4.5000)

In [80]:
# how to reshape a tensor

mean_tensor_f32 , mean_tensor_f32.shape , mean_tensor_f32.dtype , mean_tensor_f32.ndim

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([10]),
 torch.float32,
 1)

In [79]:
reshaped_tensor = mean_tensor_f32.reshape(1,1,-1)
reshaped_tensor , reshaped_tensor.shape , reshaped_tensor.ndim

(tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([1, 1, 10]),
 3)

In [87]:
reshaped_tensor_v2 = mean_tensor_f32.reshape(1,10)
reshaped_tensor_v2

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [94]:
x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]],

        [[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]],

        [[ 0.6558,  0.0566,  0.1838, -0.5983],
         [ 0.6037,  0.2153, -0.0014, -0.6023],
         [ 0.5914,  0.0809,  0.1573, -0.5555],
         [ 0.8549,  0.0615,  0.2566, -0.5615]]], grad_fn=<StackBackward0>)

In [96]:
k = torch.arange(0,10,1)
k , k.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [99]:
k_mod = k.reshape(1,-1)
k_mod , k_mod.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [101]:
k_mod_v2 = k_mod.squeeze()
k_mod_v2 , k_mod_v2.shape 

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [104]:
k_mod_v3 = k_mod_v2.unsqueeze(dim=1) # (10,1) (1,10)
k_mod_v3 , k_mod_v3.shape 

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [108]:
# permute     (10,20,1)    ->  (1,20,10)

i = torch.rand(224,228,3)
i.shape

torch.Size([224, 228, 3])

In [116]:
i_permute = torch.permute(i,(2,0,1))
i_permute.shape

torch.Size([3, 224, 228])