In [3]:
import torch

In [4]:
torch.__version__

'2.0.0+cu117'

In [5]:
# scalar 
scalar = torch.tensor(6)
scalar.item() 

6

In [6]:
# how to create a vector of tensors ?
vector = torch.tensor([7,7])
vector , vector.ndim 

(tensor([7, 7]), 1)

In [7]:
# how to identify the shape of the tensor ?
vector.shape , scalar.shape

(torch.Size([2]), torch.Size([]))

In [8]:
# matrix 
matrix = torch.tensor([[4,7],[5,6]])
matrix , matrix.ndim

(tensor([[4, 7],
         [5, 6]]),
 2)

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
d3_tensor = torch.tensor([[ [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [11]:
# creating a random tensor

random_tensor = torch.rand(size=(4,3))
random_tensor

tensor([[0.2977, 0.1525, 0.1210],
        [0.3636, 0.5054, 0.2498],
        [0.1918, 0.1841, 0.7057],
        [0.9410, 0.2564, 0.9598]])

In [12]:
# check the shape
random_tensor.shape , random_tensor.ndim

(torch.Size([4, 3]), 2)

5 min read : https://pytorch.org/docs/stable/tensors.html

In [13]:
random_tensor.dtype

torch.float32

RGB images = [red , green , blue]

In [14]:
x_tensor = torch.rand(size=(224,224,3))
x_tensor.ndim 

3

In [15]:
# zeros 
zero_tensor = torch.zeros(size=(2,2,8))
zero_tensor , zero_tensor.shape , zero_tensor.ndim , zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [16]:
# ones 
ones_tensor = torch.ones(size=(2,2,8))
ones_tensor , ones_tensor.shape , ones_tensor.ndim , ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [17]:
# arange
t_tensor = torch.arange(0,10,1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
r_tensor = torch.tensor(data=[4,5,7],
                        dtype=torch.float64,
                        device='cpu',
                        requires_grad=False
                        )
r_tensor , r_tensor.dtype , r_tensor.device

(tensor([4., 5., 7.], dtype=torch.float64), torch.float64, device(type='cpu'))

# tensor operations
1. multiply
2. addition
3. subtraction
4. division

In [43]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [44]:
x = x + 10
x

tensor([11, 12, 13])

In [45]:
x = x - 2
x 

tensor([ 9, 10, 11])

In [46]:
x = x * 2
x

tensor([18, 20, 22])

In [47]:
x = x / 2
x

tensor([ 9., 10., 11.])

In [49]:
y = x * x
y

tensor([ 81., 100., 121.])

In [50]:
x = torch.multiply(x, 10)
x

tensor([ 90., 100., 110.])

In [51]:
x = torch.matmul(x ,x)
x

tensor(30200.)

In [53]:
x.shape , x.ndim

(torch.Size([]), 0)

In [55]:
tensor_a = torch.rand(size=(2,3))
tensor_a , tensor_a.shape

(tensor([[0.6802, 0.4334, 0.6625],
         [0.6760, 0.5687, 0.5297]]),
 torch.Size([2, 3]))

In [58]:
tensor_b = torch.rand(size=(3,8))
tensor_b , tensor_b.shape

(tensor([[0.3780, 0.0443, 0.2013, 0.5000, 0.4443, 0.1294, 0.7923, 0.3101],
         [0.7134, 0.9596, 0.8909, 0.2395, 0.1049, 0.1878, 0.7750, 0.0589],
         [0.8210, 0.7077, 0.4109, 0.5564, 0.2245, 0.5715, 0.6540, 0.6550]]),
 torch.Size([3, 8]))

In [59]:
tensor_f = torch.matmul(tensor_a,tensor_b)
tensor_f

tensor([[1.1102, 0.9148, 0.7952, 0.8125, 0.4965, 0.5480, 1.3081, 0.6704],
        [1.0961, 0.9505, 0.8604, 0.7689, 0.4789, 0.4970, 1.3227, 0.5901]])

In [73]:
# manual seed generation
torch.manual_seed(42)

random_tensor = torch.rand((2,3))
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [74]:
from torch import nn

In [76]:
linear_layer = nn.Linear(in_features=6,out_features=4)

tensor_L = torch.rand(size=(4,6))

x = linear_layer(tensor_L)
x

tensor([[ 0.2759, -0.1726, -0.5514, -0.0612],
        [ 0.2677, -0.6370, -0.5424, -0.1100],
        [ 0.2907, -0.2927, -0.4526,  0.0765],
        [ 0.5037,  0.3170, -0.3585,  0.3380]], grad_fn=<AddmmBackward0>)

In [87]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [88]:
v.min()

tensor(0)

In [89]:
v.max()

tensor(14)

In [90]:
max_index = v.argmax()
max_index

tensor(7)

In [91]:
min_index = v.argmin()
min_index

tensor(0)

In [92]:
float_tensor = torch.arange(0.,10,1.)
float_tensor , float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [93]:
float_tensor = torch.arange(0,10,1)
float_tensor , float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)