In [1]:
import torch

In [2]:
torch.__version__

'2.0.0+cu117'

In [10]:
# scalar 
scalar = torch.tensor(6)
scalar.item() 

6

In [12]:
# how to create a vector of tensors ?
vector = torch.tensor([7,7])
vector , vector.ndim 

(tensor([7, 7]), 1)

In [14]:
# how to identify the shape of the tensor ?
vector.shape , scalar.shape

(torch.Size([2]), torch.Size([]))

In [16]:
# matrix 
matrix = torch.tensor([[4,7],[5,6]])
matrix , matrix.ndim

(tensor([[4, 7],
         [5, 6]]),
 2)

In [17]:
matrix.shape

torch.Size([2, 2])

In [22]:
d3_tensor = torch.tensor([[ [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [32]:
# creating a random tensor

random_tensor = torch.rand(size=(4,3))
random_tensor

tensor([[0.0234, 0.6367, 0.2483],
        [0.0071, 0.9394, 0.4519],
        [0.0798, 0.9202, 0.2634],
        [0.2307, 0.1441, 0.2281]])

In [33]:
# check the shape
random_tensor.shape , random_tensor.ndim

(torch.Size([4, 3]), 2)

5 min read : https://pytorch.org/docs/stable/tensors.html

In [34]:
random_tensor.dtype

torch.float32

RGB images = [red , green , blue]

In [41]:
x_tensor = torch.rand(size=(224,224,3))
x_tensor.ndim 

3

In [43]:
# zeros 
zero_tensor = torch.zeros(size=(2,2,8))
zero_tensor , zero_tensor.shape , zero_tensor.ndim , zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [45]:
# ones 
ones_tensor = torch.ones(size=(2,2,8))
ones_tensor , ones_tensor.shape , ones_tensor.ndim , ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [47]:
# arange
t_tensor = torch.arange(0,10,1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])