## simple mnist handwritten viz
https://tensorspace.org/html/playground/trainingLeNet.html

In [2]:
import torch

In [3]:
torch.__version__

'2.0.0+cu117'

In [4]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
# gives me the dimensions of the tensor
scalar.ndim

0

In [6]:
# gives me the tensor number  
scalar.item()

7

In [7]:
# vectors
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[5,8],[7,1]])
matrix

tensor([[5, 8],
        [7, 1]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
threed_tensor = torch.tensor([[[4,5,5],[9,7,4],[1,6,0]]])
threed_tensor

tensor([[[4, 5, 5],
         [9, 7, 4],
         [1, 6, 0]]])

In [14]:
threed_tensor.ndim

3

In [15]:
threed_tensor.shape

torch.Size([1, 3, 3])

In [16]:
random_tensors = torch.rand(size=(4,3))
random_tensors

tensor([[0.9287, 0.5077, 0.9686],
        [0.5665, 0.3669, 0.3779],
        [0.4884, 0.3057, 0.5631],
        [0.2987, 0.5016, 0.7299]])

In [17]:
random_tensors.shape

torch.Size([4, 3])

In [18]:
type(random_tensors.shape)

torch.Size

In [19]:
random_tensors.dtype

torch.float32

In [20]:
random_tensors.ndim

2

In [21]:
d3_rand_tensor = torch.rand(size=(4,3,5,1))
d3_rand_tensor

tensor([[[[0.5602],
          [0.0396],
          [0.1450],
          [0.7885],
          [0.4577]],

         [[0.8195],
          [0.1530],
          [0.6108],
          [0.9342],
          [0.5910]],

         [[0.5498],
          [0.8202],
          [0.1432],
          [0.5560],
          [0.1240]]],


        [[[0.3764],
          [0.3295],
          [0.8072],
          [0.4205],
          [0.9980]],

         [[0.0247],
          [0.3561],
          [0.4960],
          [0.7375],
          [0.2340]],

         [[0.3323],
          [0.0657],
          [0.1239],
          [0.3706],
          [0.6966]]],


        [[[0.3933],
          [0.3077],
          [0.4794],
          [0.2341],
          [0.7249]],

         [[0.5486],
          [0.8282],
          [0.7573],
          [0.2489],
          [0.0901]],

         [[0.7840],
          [0.3421],
          [0.2380],
          [0.6293],
          [0.0510]]],


        [[[0.1667],
          [0.8039],
          [0.0328],
          [0.118

In [22]:
d3_rand_tensor.ndim

4

In [23]:
zeros = torch.zeros(size=(5,7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
zeros.shape

torch.Size([5, 7])

In [25]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
ones.shape

torch.Size([3, 3])

In [46]:
ranging = torch.arange(0,1,0.2)
ranging , ranging.shape

(tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000]), torch.Size([5]))

In [47]:
like_zeros = torch.zeros_like(input=ranging)
like_zeros , like_zeros.shape

(tensor([0., 0., 0., 0., 0.]), torch.Size([5]))

In [48]:
torch.zeros(size=ranging.shape)

tensor([0., 0., 0., 0., 0.])

In [58]:
tensor_x = torch.tensor([1, 2, 3],
                        dtype=None,
                        device='cpu',
                        requires_grad=False)
tensor_x.shape , tensor_x.dtype , tensor_x.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [61]:
# mathematical operations on Tensors
tensor_x + 10 , tensor_x * 10 , tensor_x - 10 

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [62]:
torch.multiply(tensor_x,2)

tensor([2, 4, 6])

In [65]:
tensor_y = tensor_x * tensor_x
tensor_y

tensor([1, 4, 9])

In [66]:
torch.matmul(tensor_x,tensor_y)

tensor(36)

In [67]:
# it's not recommended to do that
tensor_x @ tensor_y

tensor(36)

In [68]:
tensor_a = torch.tensor(([1, 2, 3],[4, 5, 6]))
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [69]:
tensor_d = torch.tensor(([7, 4, 3],[5, 5, 3]))
tensor_d

tensor([[7, 4, 3],
        [5, 5, 3]])

In [70]:
torch.matmul(tensor_a,tensor_d)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [73]:
tensor_b = torch.transpose(tensor_d,0,1)
tensor_b

tensor([[7, 5],
        [4, 5],
        [3, 3]])

In [74]:
torch.matmul(tensor_a,tensor_b)

tensor([[24, 24],
        [66, 63]])

In [88]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [89]:
x2 = torch.t(x)
x2

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [90]:
torch.mm(x,x2)

tensor([[14, 32],
        [32, 77]])

In [91]:
torch.manual_seed(42)

In [93]:
from torch import nn 
tensor_a.shape

torch.Size([2, 3])

In [101]:
tensor_A = torch.rand(size =(3,2)) # 3 m , 2 n  (2,6)
linear = nn.Linear(in_features=2,
                   out_features=6)
x = tensor_A
output = linear(x)
output

tensor([[-0.7547, -0.0861, -0.3664,  0.1088,  0.2499, -0.4849],
        [-0.4863, -0.0699, -0.6034,  0.2668,  0.3025, -0.4456],
        [-0.6967, -0.0235, -0.4670,  0.1641,  0.1851, -0.3990]],
       grad_fn=<AddmmBackward0>)

In [107]:
c = torch.arange(0,100,10)
print(c)
c =c.max()
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor(90)

In [112]:
c.type(torch.float64).mean()

tensor(90., dtype=torch.float64)

In [118]:
c = c.type(torch.float32)
c.dtype

torch.float32

In [123]:
# argmax
c = torch.arange(0,100,10)
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [124]:
print(f'the maximum index in the tensor is {c.argmax()}')

the maximum index in the tensor is 9


In [125]:
print(f'the minimum index in the tensor is {c.argmin()}')

the minimum index in the tensor is 0
