## simple mnist handwritten viz
https://tensorspace.org/html/playground/trainingLeNet.html

In [2]:
import torch

In [3]:
torch.__version__

'2.0.0+cu117'

In [4]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
# gives me the dimensions of the tensor
scalar.ndim

0

In [6]:
# gives me the tensor number  
scalar.item()

7

In [7]:
# vectors
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[5,8],[7,1]])
matrix

tensor([[5, 8],
        [7, 1]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
threed_tensor = torch.tensor([[[4,5,5],[9,7,4],[1,6,0]]])
threed_tensor

tensor([[[4, 5, 5],
         [9, 7, 4],
         [1, 6, 0]]])

In [14]:
threed_tensor.ndim

3

In [15]:
threed_tensor.shape

torch.Size([1, 3, 3])

In [16]:
random_tensors = torch.rand(size=(4,3))
random_tensors

tensor([[0.1111, 0.1108, 0.8376],
        [0.7783, 0.2671, 0.9229],
        [0.9464, 0.6605, 0.7956],
        [0.1437, 0.6574, 0.9748]])

In [17]:
random_tensors.shape

torch.Size([4, 3])

In [18]:
type(random_tensors.shape)

torch.Size

In [19]:
random_tensors.dtype

torch.float32

In [20]:
random_tensors.ndim

2

In [21]:
d3_rand_tensor = torch.rand(size=(4,3,5,1))
d3_rand_tensor

tensor([[[[0.4981],
          [0.9707],
          [0.0314],
          [0.8037],
          [0.4997]],

         [[0.0771],
          [0.5663],
          [0.5296],
          [0.6945],
          [0.5201]],

         [[0.6668],
          [0.8853],
          [0.1033],
          [0.7054],
          [0.2518]]],


        [[[0.2328],
          [0.4211],
          [0.3290],
          [0.3018],
          [0.5696]],

         [[0.8867],
          [0.4550],
          [0.8492],
          [0.7826],
          [0.5543]],

         [[0.4231],
          [0.7819],
          [0.3818],
          [0.2788],
          [0.9336]]],


        [[[0.1653],
          [0.3972],
          [0.7607],
          [0.4393],
          [0.1523]],

         [[0.9664],
          [0.3173],
          [0.7404],
          [0.0214],
          [0.5060]],

         [[0.7249],
          [0.1504],
          [0.7733],
          [0.8547],
          [0.9366]]],


        [[[0.9811],
          [0.9064],
          [0.3107],
          [0.476

In [22]:
d3_rand_tensor.ndim

4

In [23]:
zeros = torch.zeros(size=(5,7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
zeros.shape

torch.Size([5, 7])

In [25]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
ones.shape

torch.Size([3, 3])

In [27]:
ranging = torch.arange(0,1,0.2)
ranging , ranging.shape

(tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000]), torch.Size([5]))

In [28]:
like_zeros = torch.zeros_like(input=ranging)
like_zeros , like_zeros.shape

(tensor([0., 0., 0., 0., 0.]), torch.Size([5]))

In [29]:
torch.zeros(size=ranging.shape)

tensor([0., 0., 0., 0., 0.])

In [30]:
tensor_x = torch.tensor([1, 2, 3],
                        dtype=None,
                        device='cpu',
                        requires_grad=False)
tensor_x.shape , tensor_x.dtype , tensor_x.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [31]:
# mathematical operations on Tensors
tensor_x + 10 , tensor_x * 10 , tensor_x - 10 

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [32]:
torch.multiply(tensor_x,2)

tensor([2, 4, 6])

In [33]:
tensor_y = tensor_x * tensor_x
tensor_y

tensor([1, 4, 9])

In [34]:
torch.matmul(tensor_x,tensor_y)

tensor(36)

In [35]:
# it's not recommended to do that
tensor_x @ tensor_y

tensor(36)

In [36]:
tensor_a = torch.tensor(([1, 2, 3],[4, 5, 6]))
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
tensor_d = torch.tensor(([7, 4, 3],[5, 5, 3]))
tensor_d

tensor([[7, 4, 3],
        [5, 5, 3]])

In [38]:
torch.matmul(tensor_a,tensor_d)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tensor_b = torch.transpose(tensor_d,0,1)
tensor_b

tensor([[7, 5],
        [4, 5],
        [3, 3]])

In [ ]:
torch.matmul(tensor_a,tensor_b)

tensor([[24, 24],
        [66, 63]])

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x2 = torch.t(x)
x2

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
torch.mm(x,x2)

tensor([[14, 32],
        [32, 77]])

In [ ]:
torch.manual_seed(42)

In [ ]:
from torch import nn 
tensor_a.shape

torch.Size([2, 3])

In [ ]:
tensor_A = torch.rand(size =(3,2)) # 3 m , 2 n  (2,6)
linear = nn.Linear(in_features=2,
                   out_features=6)
x = tensor_A
output = linear(x)
output

tensor([[-0.7547, -0.0861, -0.3664,  0.1088,  0.2499, -0.4849],
        [-0.4863, -0.0699, -0.6034,  0.2668,  0.3025, -0.4456],
        [-0.6967, -0.0235, -0.4670,  0.1641,  0.1851, -0.3990]],
       grad_fn=<AddmmBackward0>)

In [ ]:
c = torch.arange(0,100,10)
print(c)
c =c.max()
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor(90)

In [ ]:
c.type(torch.float64).mean()

tensor(90., dtype=torch.float64)

In [ ]:
c = c.type(torch.float32)
c.dtype

torch.float32

In [ ]:
# argmax
c = torch.arange(0,100,10)
c , c.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
print(f'the maximum index in the tensor is {c.argmax()}')

the maximum index in the tensor is 9


In [ ]:
print(f'the minimum index in the tensor is {c.argmin()}')

the minimum index in the tensor is 0


In [ ]:
# tensor data types

x = torch.arange(0.,10.,1.)
x , x.dtype 

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [ ]:
x = x.type(torch.float32)
x , x.dtype , x.shape , x.ndim

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.float32,
 torch.Size([10]),
 1)

In [ ]:
# how to reshape a tensor
x_reshaped = x.reshape(1,10)
x_reshaped , x_reshaped.shape , x_reshaped.ndim


(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]), 2)

In [ ]:
d = torch.reshape(x,(1,10))
d , d.shape , d.ndim

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]), 2)

In [ ]:
a = torch.arange(5.)
a

tensor([0., 1., 2., 3., 4.])

In [ ]:
torch.reshape(a, (2, 3))

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [ ]:
b = torch.tensor([[0, 1], [2, 3]])
b , b.ndim

(tensor([[0, 1],
         [2, 3]]),
 2)

In [ ]:
f = torch.reshape(b, (-1,)) 
f , f.ndim

(tensor([0, 1, 2, 3]), 1)

In [ ]:
f , f.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [ ]:
c = f.view(1,4)
c , c.shape

(tensor([[0, 1, 2, 3]]), torch.Size([1, 4]))

In [ ]:
f

tensor([0, 1, 2, 3])

In [ ]:
stack = torch.stack([f,f,f,f])
stack , stack.ndim , stack.shape

(tensor([[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]),
 2,
 torch.Size([4, 4]))

In [ ]:
c , c.shape

(tensor([[0, 1, 2, 3]]), torch.Size([1, 4]))

In [ ]:
squeezed_tensor = c.squeeze()
squeezed_tensor , squeezed_tensor.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [ ]:
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=0)
unsqueezed_tensor , unsqueezed_tensor.shape

(tensor([[0, 1, 2, 3]]), torch.Size([1, 4]))

In [ ]:
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=1)
unsqueezed_tensor , unsqueezed_tensor.shape

(tensor([[0],
         [1],
         [2],
         [3]]),
 torch.Size([4, 1]))

In [66]:
# (224,244,3) RGB channels
x_tensor = torch.rand(size=(224,228,3))
x_tensor.shape , x_tensor.ndim

(torch.Size([224, 228, 3]), 3)

In [68]:
x_premuted = x_tensor.permute(2,0,1)
x_premuted.shape 

torch.Size([3, 224, 228])

In [70]:
import numpy as np

In [73]:
array = np.arange(1.,8.)
array , type(array)

(array([1., 2., 3., 4., 5., 6., 7.]), numpy.ndarray)

In [75]:
to_tensor = torch.from_numpy(array)
to_tensor , type(to_tensor)

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.Tensor)

In [76]:
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [78]:
to_tensor *2

tensor([ 2.,  4.,  6.,  8., 10., 12., 14.], dtype=torch.float64)

In [92]:
# random seeds 
torch.manual_seed(42)

tensor_o = torch.rand(3,4)
tensor_o

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [93]:
# random seeds 
torch.manual_seed(43)

tensor_a = torch.rand(3,4)
tensor_a

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])

In [94]:
tensor_a == tensor_o

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [95]:
!nvidia-smi

Sun Nov 12 21:45:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8    10W /  N/A |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [96]:
# device agnostic code 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [99]:
gpus_count = torch.cuda.device_count()
gpus_count

1

In [116]:
tensor_o = torch.rand(3,4)
tensor_o

tensor([[0.1318, 0.8375, 0.5625, 0.4138],
        [0.8621, 0.2793, 0.5834, 0.3287],
        [0.6773, 0.7046, 0.9207, 0.2337]])

In [117]:
tensor_o.device

device(type='cpu')

In [123]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_x = tensor_o.to(device)
tensor_x.device

device(type='cuda', index=0)

In [126]:
tensor_y = tensor_x.cpu().numpy()
tensor_y , type(tensor_y)

(array([[0.13180745, 0.8374526 , 0.5625421 , 0.4138319 ],
        [0.86205226, 0.27930474, 0.58342195, 0.32874966],
        [0.67729884, 0.7045715 , 0.9206977 , 0.23374915]], dtype=float32),
 numpy.ndarray)